### ISSUE TITLE
Rewrite the inactivity commands

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#1]

**Comment by CaptainDestructo** [comment]
Note to whoever picks up the inactivity commands:

I have added Leave of Absence processing to the bot. Leaves of absence are stored in MySQL table LeaveTimes, with fields officer_id, date_start, date_end, reason.

Inactivity commands will need to check officer ID against this table, and if there is an entry with matching officer ID, bypass inactivity.

**Comment by CaptainDestructo** [comment]
Inactivity commands are functional. If more commands are needed, please advise.
