### ISSUE TITLE
Archival of Detentions

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#3]
The idea here is that we have multiple channels where people are taken in for detention, like detention-1, detention-2 and detention-3.

When a command is run in the channel it should move the channel down to a specified category, as long as that category isn't full, otherwise it creates another category like "Archive - Detention 3".

After this the channel's permissions are since in order to hide the channel from everyone except Deputy Chiefs and Chiefs.

**Comment by egasvegas1109** [comment]
12345

**Comment by CaptainDestructo** [comment]
This feature is up and running in the test server with prefix `!`
