### ISSUE TITLE
Secure Web UI

### ISSUE THREAD

**Issue by CaptainDestructo** [LPD-VRChat/LPD-Officer-Monitor#36]
Concept to be fleshed out at a later date:

Web interface for the bot, to allow Event Hosts, Dispatch, Staff, and other team members to log in using their Discord acount (OAuth2 integration).

Such an interface would ideally provide handy dispatching tools, such as a better layout for squads, showing the avatar and VRChat world in use by each user. Click on a user to select them as squad lead. Automatic event attendance! Automatic formatting and posting for SLRT/LMT calls, with a visual of what teams are dispatched to them. Automatically mark the call resolved when the squads split up.

There are an infinite number of possibilities here, just have to get things started. Baby steps.

**Comment by 50thomatoes50** [comment]
Suggestions : use nginx as facing Webserver.
It is really efficient to serve static data.
And use reverse proxy to connect to the bot API.
Also settings up Let's encrypt for nginx is super easy and it will also auto renew the certificate.
 Sadly using cloudflare will break autorenew

**Comment by CaptainDestructo** [comment]
Update on this project:

I have the WebManager code running correctly using templates and with clean shutdown behavior. SSL is enabled, although it needs to be manually configured on initial setup for the host it's being run from. This will break SSL if testing the code while not on devbox. I may add an option to disable SSL at launch, or if the certificate files do not exist, then launch in insecure mode.

**Comment by CaptainDestructo** [comment]
Look into importlib.reload to reload modules, and potentially figure out how to stop and start serve. It will stop if the awaitable it is handed as the shutdown_event returns.

**Comment by CaptainDestructo** [comment]
Adding this comment for a bit of documentation/progress report.

The WebManager class handles all processing of all pages and API endpoints. All functions contained within WebManager should be directly related to the rendering or delivery of a webpage or payload.

Page paths should be directoried. IE, the Dispatch page uses javascript to load in tables from the server. The code that generates those tables is located underneath the Dispatch path.

All API endpoints should be under `/api/action` or `/api/resource`. Certain ones may have an alias under `/api` root, such as the authentication.

All API endpoints should utilize JSON where possible, unless it is a custom protocol such as the image role processing.
