### ISSUE TITLE
Improve shutdown behavior

### ISSUE THREAD

**Issue by CaptainDestructo** [LPD-VRChat/LPD-Officer-Monitor#39]
Capture Keyboard Interrupt signals from the console and perform a clean shutdown.

A clean shutdown should:
* cause zero Python errors if possible
* stop and log time for Officers on-duty

**Comment by CaptainDestructo** [comment]
So it appears that the primary cause of the exceptions on shutdown would be Quart. Quart expects to be run as its own application more or less. I will be requesting the devs to add the option to disable loop management in Quart. @hrolfurgylfa

**Comment by hrolfurgylfa** [comment]
I doubt that will get anywhere.

I think our best option is to either look into someone has already forked it, and added this feature or to do it ourselves. Worst case scenario we can be a shutdown command in discord, but that is our last option.

**Comment by CaptainDestructo** [comment]
Quart is actively maintained, so I will wait a little bit on this issue to see if I get a response.

Also, it doesn't have to be just a shutdown command in discord. I can write a prompt in the console where you could type `shutdown` instead of ^C and perform a clean shutdown.

**Comment by CaptainDestructo** [comment]
Just an update on this issue:

I am implementing the clean shutdown inside the WebManager branch. It's fairly simple, although I haven't tested it in the absence of WebManager. Since we're going to be looking at the WebManager code soon anyways, I'm not going to bother branching for just this feature (not yet anyways).
