### ISSUE TITLE
Automatically handle LOA requests.

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#4]
This idea is to automatically check all the LOA requests #leave-of-absence. The bot would check the sender's formatting when a new one is sent and if it doesn't follow the pinned example the bot would delete it, let the person who sent it know and the bot would then send the senders their message content so that they can redo it.

The reason it would strictly require the specific format is because with that we could have the bot automatically delete ones that have run out or if they aren't 1-3 months.

What I though about is at least that if a LOA message is edited it would also re-check it and verify that it follows the format. This would require the on_raw_message_edit event as on_message_edit is only run for cached messages.

**Comment by CaptainDestructo** [comment]
LOA requests are automatically stored in `LeaveTimes` with primary key `officer_id`.
If another message is sent with matching `officer_id`, the record is updated.
Date range is parsed to check for validity, and has error handling.

**Comment by CaptainDestructo** [comment]
Leave of Absence request processing is functional. This has also been integrated into the Inactivity commands.
