### ISSUE TITLE
Rewrite the ?count_officers command

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#5]
This command just counts and displays how many people we have of each rank, nothing very complicated.

It can also be basically copied from the 1.0 bot.

**Comment by CaptainDestructo** [comment]
Updated commands.py - has not been tested
[commands.py.txt](https://github.com/hrolfurgylfa/LPD-Officer-Monitor/files/5344138/commands.py.txt)

**Comment by CaptainDestructo** [comment]
Updated commands.py - has not been tested

[commands.zip](https://github.com/hrolfurgylfa/LPD-Officer-Monitor/files/5344169/commands.zip)

**Comment by CaptainDestructo** [comment]
Mark solved on fulfillment of pull request.
