### ISSUE TITLE
Formatting for =patrol_time -l breaks when giving more than one message of information

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#53]
This can be seen here:
![image](https://user-images.githubusercontent.com/33896457/114090785-65cfa700-98a7-11eb-88de-70eda544e3d2.png)

**Comment by CaptainDestructo** [comment]
This also appears to be an issue:
![image](https://user-images.githubusercontent.com/72361870/116489157-e0ae3100-a859-11eb-8a0a-d03cf5eb63a7.png)
