### ISSUE TITLE
SLRT Badge System

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#68]
A SLRT badge system where a member can be given a badge, like 101, after the training and they only get the SLRT role when they're finished getting all the badges.

This needs a lot more discussion on both the UX side and the implementation part so please don't start on a pull request before we decide on that here in this issue.

**Comment by CaptainDestructo** [comment]
So basically automate SLRT’s internal recordkeeping?

**Comment by hrolfurgylfa** [comment]
Yeah, basically.

I also want to try to design this in a way to work for more than just the SLRT team, like LMT team or maybe even just general LPD badges, with only a change in the settings.

Currently I'm thinking a command for someone with a specific role (or white shirt) in team_bot_channel or admin_bot_channel that gives a badge. And than people can view their badges in # general-bot-channel with a command

**Comment by hrolfurgylfa** [comment]
I'm thinking an embed like this might be decent for officers to view their badges:
![image](https://user-images.githubusercontent.com/33896457/118833762-3bfb9e00-b8b1-11eb-8d0c-7b25b8a1df3f.png)

This is of course a rough mocup, we'll need to talk to the media team before finishing the feature and see if they are able to make a image there that fits, instead of the crappy logo I found in a logo generator and we'll also probably have to change the emojis for if you have the badge or not, we can use custom emojis though.

Here is [the website I used to generate this](https://leovoel.github.io/embed-visualizer/) and the JSON:
```json
{
  "embed": {
    "title": "Your Badges",
    "description": "⠀",
    "color": 191396,
    "thumbnail": {
      "url": "https://cdn.discordapp.com/attachments/566806197815214110/844586680483577857/unknown.png"
    },
    "image": {
      "url": ""
    },
    "author": {
      "name": "Hroi",
      "icon_url": "https://cdn.discordapp.com/avatars/378666988412731404/a_6db5d83c4128df4a2ae701cded26ee91.webp?size=512"
    },
    "fields": [
      {
        "name": "SLRT",
        "value": "✅ SLRT 101\n❎ SLRT 201\n⠀"
      },
      {
        "name": "LMT",
        "value": "✅ SLRT 101\n❎ SLRT 201"
      }
    ]
  }
}
```

**Comment by CaptainDestructo** [comment]
UI looks pretty good, but how will that information be stored? Another table? Discord roles?

**Comment by hrolfurgylfa** [comment]
We can't store it in discord roles, so it will have to be another database table.

Ideally this would be stored within the database as a table with rank roles, and with a many to many relation ship to the Officer. But if we want to adjust this through settings, we need to do it some other way. We could maybe do that though, and then have it addable through commands, but that might be unnecessarily complex.
