### ISSUE TITLE
Adjust inactivity system before next inactive sweep

### ISSUE THREAD

**Issue by hrolfurgylfa** [LPD-VRChat/LPD-Officer-Monitor#69]
The parameters for someone to be marked as inactive need to be changed slightly.

1 hour within the last 60 days.
Or a message in a monitored channel in the last 14 days.

**Comment by CaptainDestructo** [comment]
I’ll take care of it this week/weekend

**Comment by hrolfurgylfa** [comment]
@CaptainDestructo I'm already working on this one

**Comment by hrolfurgylfa** [comment]
I've got the functionality finished in the inactivity-system-adjustments branch. I probably need to refactor the code though, since it's really hard to read.
